import { authConroller } from '@/libs/formulas/auth/data-access/src';
import './global.css';
import { Header } from '@/libs/formulas/layouts/src';
import { Toaster } from '@/ui/toaster';
import { CheckAuth } from '@/libs/formulas/auth/data-access/src';
export const metadata = {
  title: 'Welcome to apps/frontend/formulas',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CheckAuth>
          <Header />
          {children}
          <Toaster />
        </CheckAuth>
      </body>
    </html>
  );
}
